name = "ApplySOM"
uuid = "2d54c9ec-8019-4fa9-998d-b6585e62b6b2"
authors = ["Kwang-Seuk <kjeong@bhug.ac.kr> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
